spring.application.name=patient_data
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=false
spring.datasource.url=jdbc:postgresql://dpg-d40dvs3uibrs73b9oeb0-a.render.com/patient_db_1f9n
spring.datasource.username=patient_db_1f9n_user
spring.datasource.password=RsmMiOtNNwQhBab8x5EpFSrlzNXrzUIV
